version: 0.1
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - printenv
      - npm install
      - npm install -g serverless
  post_build:
    commands:
      - serverless deploy --stage dev